### PR TITLE
Doc updates clarifying 3 features

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
clarifying 3 features in docs.

### CODE REVIEW

**Comment by ChengyuanZhao** [comment]
@meltsufin Would you mind merging this one? this thing thinks i need to sign a CLA but I can't because   I'm a googler.

**Comment by meltsufin** [comment]
It's blocking the merge. I think you just put the wrong email somewhere in the commit.

**Comment by meltsufin** [comment]
I fixed the commit.

**Comment by ChengyuanZhao** [comment]
Oh shoot, sorry I might have undone your fix by accident. Would you mind doing that again :D

**Comment by meltsufin** [comment]
Sure.

**Pull request merged**
